In [1]:
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setInverse <- function(inverse) inv <<- inverse
        getInverse <- function() inv
        list(set = set,
             get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getInverse()
        if (!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        mat <- x$get()
        inv <- solve(mat, ...)
        x$setInverse(inv)
        inv
}

In [2]:
my_matrix <- makeCacheMatrix(matrix(1:4, 2, 2))

In [3]:
my_matrix$get()

[,1] [,2]
[1,]    1    3
[2,]    2    4

In [4]:
my_matrix$getInverse()

NULL

In [5]:
cacheSolve(my_matrix)

[,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

In [6]:
cacheSolve(my_matrix)

getting cached data


[,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

In [7]:
my_matrix$getInverse()

[,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

In [8]:
my_matrix$set(matrix(c(2, 2, 1, 4), 2, 2))

In [9]:
my_matrix$get()

[,1] [,2]
[1,]    2    1
[2,]    2    4

In [10]:
my_matrix$getInverse()

NULL

In [11]:
cacheSolve(my_matrix)

[,1]       [,2]
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333

In [12]:
cacheSolve(my_matrix)

getting cached data


[,1]       [,2]
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333

In [13]:
my_matrix$getInverse()

[,1]       [,2]
[1,]  0.6666667 -0.1666667
[2,] -0.3333333  0.3333333